Update jitpack script to try more times and wait longer

diff --git a/.github/workflows/jitpack_build.yml b/.github/workflows/jitpack_build.yml
--- a/.github/workflows/jitpack_build.yml
+++ b/.github/workflows/jitpack_build.yml
@@ -17,19 +17,23 @@ jobs:
         echo "Triggering JitPack build"
         
         PACKAGES_URL="https://jitpack.io/com/github/${GITHUB_REPOSITORY}/${GITHUB_REF#refs/tags/}/"
-        
-        # Try the URL 3 times before failing
+        PACKAGES_FILE="packages.txt"
+        touch ${PACKAGES_FILE}
+        # Try the URL 6 times before failing
         count=1
-        until [[ $count -gt 3 ]] || [[ ${FILE_COUNT:-0} -gt 1 ]]; do
-          echo "Attempt ${count}/3"
-          FILES=$(curl -sS --max-time 900 ${PACKAGES_URL})
-          FILE_COUNT=$(echo ${FILES} | wc -w | xargs)
+        until [[ $count -gt 6 ]] || [[ $(cat c${PACKAGES_FILE} | wc -l | xargs ) -gt 1 ]] ; do
+          echo "Attempt ${count}/6"
+          STATUS=$(curl -s -o packages.txt -w "%{http_code}" --max-time 900 ${PACKAGES_URL})
+          
           let count+=1
-          sleep 5
+          sleep 30
         done
         
         echo "::group::Files Available"
-        echo ${FILES}
+        echo $(cat ${PACKAGES_FILE})
         echo "::endgroup::"
         
-        if [[ $count -gt 3 ]]; then exit 1; fi
+        if [[ ${STATUS} -gt 399 ]] ; then
+          echo "FAILURE: ${STATUS} response from JitPack"
+          exit 1 
+        fi
